// web/ui/src/react/use-auth.ts
import { useSyncExternalStore, useCallback } from 'react';
import { getAuthClient } from '../auth/index.js';
import type { User } from '../auth/types.js';

export function useAuth(): { user: User | null; isAuthenticated: boolean } {
  const client = getAuthClient();
  const subscribe = useCallback((cb: () => void) => {
    client.on('change', cb);
    client.on('logout', cb);
    return () => { client.off('change', cb); client.off('logout', cb); };
  }, [client]);
  const getSnapshot = useCallback(() => client.getUser(), [client]);
  const user = useSyncExternalStore(subscribe, getSnapshot);
  return { user, isAuthenticated: user !== null };
}

// web/ui/src/solid/use-auth.ts
import { createSignal, onCleanup } from 'solid-js';
import { getAuthClient } from '../auth/index.js';
import type { User } from '../auth/types.js';

export function useAuth() {
  const client = getAuthClient();
  const [user, setUser] = createSignal<User | null>(client.getUser());
  const isAuthenticated = () => user() !== null;

  const onChange = (u: User | null) => setUser(u);
  const onLogout = () => setUser(null);
  client.on('change', onChange);
  client.on('logout', onLogout);
  onCleanup(() => { client.off('change', onChange); client.off('logout', onLogout); });

  return { user, isAuthenticated };
}
