// web/ui/src/react/use-theme.ts
import { useSyncExternalStore, useCallback } from 'react';

type Theme = 'dark' | 'light';

function getTheme(): Theme {
  if (typeof document === 'undefined') return 'dark';
  return (document.documentElement.getAttribute('data-theme') as Theme) ?? 'dark';
}

export function useTheme(): Theme {
  const subscribe = useCallback((cb: () => void) => {
    if (typeof document === 'undefined') return () => {};
    const obs = new MutationObserver(() => cb());
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
    return () => obs.disconnect();
  }, []);
  return useSyncExternalStore(subscribe, getTheme, () => 'dark' as Theme);
}

// web/ui/src/solid/use-theme.ts
import { createSignal, onCleanup } from 'solid-js';

type Theme = 'dark' | 'light';

function getCurrentTheme(): Theme {
  if (typeof document === 'undefined') return 'dark';
  return (document.documentElement.getAttribute('data-theme') as Theme) ?? 'dark';
}

export function useTheme() {
  const [theme, setTheme] = createSignal<Theme>(getCurrentTheme());
  if (typeof document !== 'undefined') {
    const obs = new MutationObserver(() => setTheme(getCurrentTheme()));
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
    onCleanup(() => obs.disconnect());
  }
  return theme;
}
