// web/packages/react/src/use-permissions.ts
import { useState, useCallback } from 'react';
import { PermissionSet } from '@workfort/ui';

export function usePermissions(initial: string[] = []) {
  const [core] = useState(() => new PermissionSet(initial));
  const [, setVersion] = useState(0); // trigger re-render on update

  const can = useCallback((permission: string) => core.can(permission), [core]);

  const update = useCallback((perms: string[]) => {
    core.update(perms);
    setVersion((v) => v + 1);
  }, [core]);

  return { can, update };
}

// web/packages/solid/src/use-permissions.ts
import { createSignal } from 'solid-js';
import { PermissionSet } from '@workfort/ui';

export function usePermissions(initial: string[] = []) {
  const core = new PermissionSet(initial);
  const [permissions, setPermissions] = createSignal<string[]>(initial);

  function can(permission: string): boolean {
    return core.can(permission);
  }

  function update(perms: string[]): void {
    core.update(perms);
    setPermissions(perms);
  }

  return { can, update, permissions };
}
