// web/packages/react/src/use-idle-detection.ts
import { useEffect, useRef } from 'react';
import { IdleDetector, type IdleDetectorOptions } from '@workfort/ui';

export function useIdleDetection(opts: IdleDetectorOptions): void {
  const detectorRef = useRef<IdleDetector | null>(null);

  useEffect(() => {
    const detector = new IdleDetector(opts);
    detector.start();
    detectorRef.current = detector;
    return () => detector.dispose();
  }, []);
}

// web/packages/solid/src/use-idle-detection.ts
import { onCleanup } from 'solid-js';
import { IdleDetector, type IdleDetectorOptions } from '@workfort/ui';

export function useIdleDetection(opts: IdleDetectorOptions): IdleDetector {
  const detector = new IdleDetector(opts);
  detector.start();
  onCleanup(() => detector.dispose());
  return detector;
}
